### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by zarry**
This should be a pretty decent start.  The only thing I didn't touch on that deserves mentioning is the chef-vault stuff as I don't use that so I couldn't really discuss. 

Feel free to take or scrap all of it :)

### CODE REVIEW

**Comment by johnbellone** [comment]
Can you rebase?

**Comment by zarry** [comment]
updated!

**Comment by johnbellone** [comment]
I am still on the fence about providing a table for resource properties (attributes). I am wondering if its useful at all? It could cause a drift in the documentation and I think its much clearer to just look at the code.

**Comment by zarry** [comment]
100% agree. I was on the fence and ended up going this route as I believe I noticed that is what you had in the consul cookbook before you pushed the latest updates. :)  Same reason I did away with the attribute table as I didn't think that was necessary. 

I think as long as we are clear in that vault properties can be dropped right into the ['server'] or ['config'] attributes and they will end up in the configuration file properly is the ultimate goal.  That is what I personally love about how you built these cookbooks btw...

**Pull request closed without merging**
