### PR TITLE
use new_resource.name as type

### LINKED ISSUE #222: `new_resource.name` not being used for type property?
## :ghost: Brief Description

For several resources, seeing `type is a required property`, while the docs indicate this property should be picked up from the resource name. These resources include, but may not be limited to:

* hashicorp_vault_config_storage
* hashicorp_vault_config_listener
* hashicorp_vault_config_seal 

## :pancakes: Cookbook version

6.0.3

## :woman_cook:  Chef-Infra Version

17.3.48

## :tophat: Platform details

rockylinux 8 on ec2

## Steps To Reproduce

Create a resource of (for example) type `hashicorp_vault_config_storage`, like so:

```
## Storage
hashicorp_vault_config_storage 'consul' do
  config_file node['vault']['config']['file']
  options(
    address:  node['vault']['config']['storage_options']['address'],
    path:     node['vault']['config']['storage_options']['path']
  )
  notifies_delayed :restart, 'hashicorp_vault_service[vault]'
end
```

## :police_car: Expected behavior

If I'm reading the docs correctly, this should work. Instead it says that `type is a required property`. The work-around here is to add `type 'consul'` to the resource definition.

## :heavy_plus_sign: Additional context

This isn't a huge deal, the work around is simple. Logging the issue because it looks like the behavior doesn't match the doc.

### PR DESCRIPTION
**Pull request by mbaitelman**
# Description

Updates resources to match docs

## Issues Resolved

Closes #222 

## Check List

- [X] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by Xorima** [comment]
Is this breaking change as if people have named things differently they could have a shock or does it not impact even if the type is changed? (not a vault guy)

**Comment by mbaitelman** [comment]
I'm not familiar with vault either but from the chef side, this should not break anything. 
The name property is always overridden by the :type property anyway.
As everyone currently has the type parameter (otherwise it was broken) this will only start being used when folks start leaving out the type parameter.

**Comment by mbaitelman** [comment]
It looks like the failing tests are not from my changes 
https://github.com/sous-chefs/hashicorp-vault/runs/3877853384?check_suite_focus=true

**Comment by mbaitelman** [comment]
Tests are fixed. 
This can be merged.

**Pull request merged**
