### PR TITLE
Fix tls_disable with vault 0.2.0

### PR DESCRIPTION
**Pull request by zarry**
This fix should be backwards compatible but I have not tested.  Resolving issue https://github.com/johnbellone/vault-cookbook/issues/8 which I filed earlier.

### CODE REVIEW

**Comment by zarry** [comment]
Not sure this is the proper fix. even based on the golang documentation for ParseBoolean which states "false" is parsed as false, I think it is taking any value in this field and setting tls_disable to true.  I tested with both "0" and "false".  When either of these are present vault disables tls.

**Comment by zarry** [comment]
take 2 on this fix.  Not sure this is exactly how you want to go about it, but it is working for me at this point. feel free to touch base to discuss.

**Comment by johnbellone** [comment]
What's the issue here?

**Comment by zarry** [comment]
The vault server wouldn't start with empty string for tls_disable. 

```
% sudo su -c "vault server -config=/home/vault/.vault.json" -s /bin/sh vault
Error detecting advertise address: tls_disable: strconv.ParseBool: parsing "": invalid syntax
Error initializing core: missing advertisement address
```

**Comment by jeffbyrnes** [comment]
As per the [Vault docs on `tls_disable`](https://vaultproject.io/docs/config/#tls_disable):

> tls_disable (optional) - If non-empty, then TLS will be disabled. This is an opt-in; Vault assumes by default that TLS will be used.

So it should either be present to disable, or absent to leave TLS enabled.

**Pull request closed without merging**
