### PR TITLE
Future proof config

### PR DESCRIPTION
**Pull request by jeffbyrnes**
This one’s a doozy, but you can read the commit message for 1d4d0455674773e693f77142e11408adfc9c64ac to get up to speed.

Basically, the Vault config can change, and this cookbook’s `vault_config` is prescriptive about how that config is handled. Instead, we can just directly convert the `node[vault][config]` attribute into the necessary JSON.

We _do_ lose some error handling & defaults, but Vault is a software that must be custom configured for one’s environment regardless, so I trust that anyone taking advantage of this cookbook will be able to handle that.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
Rebased as per recent merges. Unfortunately, this depends at the moment on #13, though I might be able to pull that out of here if it turns out that PR is unwanted.

**Comment by johnbellone** [comment]
I am open to adding an options collector [similar to what I just did with the Consul cookbook](https://github.com/johnbellone/consul-cookbook/commit/2d415d89a28b8a448b0f94fe6f58adcc1a32d17c) but I do not want to give up on having specific attributes validated.

**Comment by jeffbyrnes** [comment]
@johnbellone a stance I can understand, but it seems as though you will forever be playing catch-up to Vault itself, esp. if the validity of certain values changes (rendering the validation in this cookbook incorrect).

I’m more of the school of thought that simpler is better, and that an operator will read the docs, and suss out any failures on the part of Vault while writing their wrapper cookbook.

Any chance I can convince you to let go of the validations in favor of letting Vault validate its own config at runtime? It has pretty good error reporting on that stuff (as I discovered while working on this).

**Comment by jeffbyrnes** [comment]
@johnbellone actually, after using the current incarnation of the cookbook w/ the manage_certificate stuff merged in, I’m quite alright to refactor this PR to follow the model you’ve espoused. Works well, and it’s your cookbook, after all.

I’ll try to get this cleaned up, and add an options collector as the “future-proof” mechanism.

**Comment by scalp42** [comment]
@jeffbyrnes did you get to it by any chance?

**Comment by jeffbyrnes** [comment]
@scalp42 I haven’t, and probably won’t get a chance for at least another week. Looking to tackle yourself?

**Pull request closed without merging**
