### PR TITLE
Add missing Vault versions and update configuration options

### LINKED ISSUE #100: Generated configuration contains 'backend' which is not a valid configuration option?
With my cookbook attributes looking like this:

    default['hashicorp-vault']['version'] = '0.7.3'

    default['hashicorp-vault']['config']['habackend_type'] = 'consul'
    default['hashicorp-vault']['config']['habackend_options']['address'] = '127.0.0.1:8500'
    default['hashicorp-vault']['config']['habackend_options']['check_timeout'] = '10s'
    default['hashicorp-vault']['config']['habackend_options']['disable_registration'] = false
    default['hashicorp-vault']['config']['habackend_options']['path'] = 'vault/'
    default['hashicorp-vault']['config']['habackend_options']['scheme'] = 'http'

    default['hashicorp-vault']['config']['tls_disable'] = true

I get a configuration that looks like this:

    {
      "disable_mlock": false,
      "listener": {
        "tcp": {
          "address": "127.0.0.1:8200",
          "tls_disable": "true"
        }
      },
      "backend": {
        "inmem": {
        }
      },
      "ha_backend": {
        "consul": {
          "address": "127.0.0.1:8500",
          "check_timeout": "10s",
          "disable_registration": false,
          "path": "vault/",
          "scheme": "http"
        }
      }
    }

Vault complains that:

    Error loading configuration from /etc/vault/vault.json: error parsing 'ha_backend': ha_backend.consul: At -: root.disable_registration: unknown type for string *ast.LiteralType

But if I change `ha_backend` to `storage` everything works. However `storage` is not a valid configuration option (see #95). So how do I get the cookbook to generate the correct configuration file?

### PR DESCRIPTION
**Pull request by josqu4red**
This change adds all missing Vault versions SHA sums, from 0.7.0 to 0.8.3.
`vault_config` resource is updated to support new configuration options and remove deprecated ones.

This change would break compatibility with Vault < 0.7.0, so I would suggest to bump cookbook major version.

Fixes #100

### CODE REVIEW

**Comment by johnbellone** [comment]
Would you mind fixing the test to accept the new default version?

**Comment by josqu4red** [comment]
@johnbellone done, should have done this in thef first place...
Tests pass locally aside from Foodcritic offenses from newer version, but it seems there are network issues with Travis.

**Comment by mitch-roblox** [comment]
Hello, I'm waiting on this PR. It looks like Travis had transient failures, would it be possible to re-run and see if it passes now?

**Comment by johnbellone** [comment]
Yep, ran it again.

**Comment by josqu4red** [comment]
🎉  thanks!

**Pull request merged**
