### PR TITLE
Fixes foodcritic, previous fix caused all checks to be ignored

### PR DESCRIPTION
**Pull request by madeddie**
The .foodcritic in its current form causes foodcritic not to check a single rule.

If you don't like these fixes, I can create a .foodcritic that skips these specific rules.

### CODE REVIEW

**Comment by legal90** [comment]
@johnbellone `package` method in `vault_installation_package` looks weird. Is it a [built-in Chef resource](https://docs.chef.io/resource_package.html) or some poise wrapper? If first, then maybe we should just remove `checksum` attribute and replace `action :uninstall` with `action :remove`?

**Comment by madeddie** [comment]
If it's a wrapper, it might be best to rename it to some custom name, so foodcritic doesn't get worried.

**Comment by johnbellone** [comment]
That method should be the built-in package resource, and it should choose the appropriate provider based on the platform. In newer cookbooks, because of Ruby's shadowing, [we've modified what we call these variables](https://github.com/bloomberg/redis-cookbook/blob/master/libraries/redis_installation_package.rb#L111-L118). In following the naming convention there it would be *system_package_checksum* and that would come from `options[:package_checksum]`.

**Comment by legal90** [comment]
Thanks, I got it. Actually, I thought that action `:uninstall` and attribute `checksum` are not supported for `package` resource because they are not mentioned in the Chef documentation.

But it seems like they are supported for windows:
https://github.com/chef/chef/blob/1991cf97660a38e704eb4cd9609ed6ea84a35442/lib/chef/resource/windows_package.rb#L51
https://github.com/chef/chef/blob/1991cf97660a38e704eb4cd9609ed6ea84a35442/lib/chef/resource/chocolatey_package.rb#L27

So, about the PR - it looks good to me

**Comment by legal90** [comment]
@madeddie Thanks for the contribution! 👍

**Pull request merged**
